// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Agenda.proto

package com.representacao;

public final class Person {
  private Person() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PessoaOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string nome = 1;
    boolean hasNome();
    String getNome();
    
    // required string endereco = 2;
    boolean hasEndereco();
    String getEndereco();
    
    // required string numeroDeTelefone = 3;
    boolean hasNumeroDeTelefone();
    String getNumeroDeTelefone();
  }
  public static final class Pessoa extends
      com.google.protobuf.GeneratedMessage
      implements PessoaOrBuilder {
    // Use Pessoa.newBuilder() to construct.
    private Pessoa(Builder builder) {
      super(builder);
    }
    private Pessoa(boolean noInit) {}
    
    private static final Pessoa defaultInstance;
    public static Pessoa getDefaultInstance() {
      return defaultInstance;
    }
    
    public Pessoa getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.representacao.Person.internal_static_representacao_Pessoa_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.representacao.Person.internal_static_representacao_Pessoa_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string nome = 1;
    public static final int NOME_FIELD_NUMBER = 1;
    private java.lang.Object nome_;
    public boolean hasNome() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nome_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string endereco = 2;
    public static final int ENDERECO_FIELD_NUMBER = 2;
    private java.lang.Object endereco_;
    public boolean hasEndereco() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getEndereco() {
      java.lang.Object ref = endereco_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          endereco_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEnderecoBytes() {
      java.lang.Object ref = endereco_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        endereco_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string numeroDeTelefone = 3;
    public static final int NUMERODETELEFONE_FIELD_NUMBER = 3;
    private java.lang.Object numeroDeTelefone_;
    public boolean hasNumeroDeTelefone() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getNumeroDeTelefone() {
      java.lang.Object ref = numeroDeTelefone_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          numeroDeTelefone_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNumeroDeTelefoneBytes() {
      java.lang.Object ref = numeroDeTelefone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        numeroDeTelefone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      nome_ = "";
      endereco_ = "";
      numeroDeTelefone_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNome()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndereco()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNumeroDeTelefone()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNomeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getEnderecoBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNumeroDeTelefoneBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNomeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEnderecoBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNumeroDeTelefoneBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.representacao.Person.Pessoa parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.representacao.Person.Pessoa parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.representacao.Person.Pessoa parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.representacao.Person.Pessoa parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.representacao.Person.Pessoa parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.representacao.Person.Pessoa parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.representacao.Person.Pessoa parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.representacao.Person.Pessoa parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.representacao.Person.Pessoa parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.representacao.Person.Pessoa parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.representacao.Person.Pessoa prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.representacao.Person.PessoaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.representacao.Person.internal_static_representacao_Pessoa_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.representacao.Person.internal_static_representacao_Pessoa_fieldAccessorTable;
      }
      
      // Construct using com.representacao.Person.Pessoa.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        nome_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        endereco_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        numeroDeTelefone_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.representacao.Person.Pessoa.getDescriptor();
      }
      
      public com.representacao.Person.Pessoa getDefaultInstanceForType() {
        return com.representacao.Person.Pessoa.getDefaultInstance();
      }
      
      public com.representacao.Person.Pessoa build() {
        com.representacao.Person.Pessoa result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.representacao.Person.Pessoa buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.representacao.Person.Pessoa result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.representacao.Person.Pessoa buildPartial() {
        com.representacao.Person.Pessoa result = new com.representacao.Person.Pessoa(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nome_ = nome_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.endereco_ = endereco_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.numeroDeTelefone_ = numeroDeTelefone_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.representacao.Person.Pessoa) {
          return mergeFrom((com.representacao.Person.Pessoa)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.representacao.Person.Pessoa other) {
        if (other == com.representacao.Person.Pessoa.getDefaultInstance()) return this;
        if (other.hasNome()) {
          setNome(other.getNome());
        }
        if (other.hasEndereco()) {
          setEndereco(other.getEndereco());
        }
        if (other.hasNumeroDeTelefone()) {
          setNumeroDeTelefone(other.getNumeroDeTelefone());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNome()) {
          
          return false;
        }
        if (!hasEndereco()) {
          
          return false;
        }
        if (!hasNumeroDeTelefone()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              nome_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              endereco_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              numeroDeTelefone_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string nome = 1;
      private java.lang.Object nome_ = "";
      public boolean hasNome() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNome(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nome_ = value;
        onChanged();
        return this;
      }
      public Builder clearNome() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      void setNome(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        nome_ = value;
        onChanged();
      }
      
      // required string endereco = 2;
      private java.lang.Object endereco_ = "";
      public boolean hasEndereco() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getEndereco() {
        java.lang.Object ref = endereco_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          endereco_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEndereco(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        endereco_ = value;
        onChanged();
        return this;
      }
      public Builder clearEndereco() {
        bitField0_ = (bitField0_ & ~0x00000002);
        endereco_ = getDefaultInstance().getEndereco();
        onChanged();
        return this;
      }
      void setEndereco(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        endereco_ = value;
        onChanged();
      }
      
      // required string numeroDeTelefone = 3;
      private java.lang.Object numeroDeTelefone_ = "";
      public boolean hasNumeroDeTelefone() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getNumeroDeTelefone() {
        java.lang.Object ref = numeroDeTelefone_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          numeroDeTelefone_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNumeroDeTelefone(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        numeroDeTelefone_ = value;
        onChanged();
        return this;
      }
      public Builder clearNumeroDeTelefone() {
        bitField0_ = (bitField0_ & ~0x00000004);
        numeroDeTelefone_ = getDefaultInstance().getNumeroDeTelefone();
        onChanged();
        return this;
      }
      void setNumeroDeTelefone(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        numeroDeTelefone_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:representacao.Pessoa)
    }
    
    static {
      defaultInstance = new Pessoa(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:representacao.Pessoa)
  }
  
  public interface ResultadoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string resultado = 1;
    boolean hasResultado();
    String getResultado();
  }
  public static final class Resultado extends
      com.google.protobuf.GeneratedMessage
      implements ResultadoOrBuilder {
    // Use Resultado.newBuilder() to construct.
    private Resultado(Builder builder) {
      super(builder);
    }
    private Resultado(boolean noInit) {}
    
    private static final Resultado defaultInstance;
    public static Resultado getDefaultInstance() {
      return defaultInstance;
    }
    
    public Resultado getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.representacao.Person.internal_static_representacao_Resultado_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.representacao.Person.internal_static_representacao_Resultado_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string resultado = 1;
    public static final int RESULTADO_FIELD_NUMBER = 1;
    private java.lang.Object resultado_;
    public boolean hasResultado() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getResultado() {
      java.lang.Object ref = resultado_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          resultado_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getResultadoBytes() {
      java.lang.Object ref = resultado_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        resultado_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      resultado_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasResultado()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getResultadoBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getResultadoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.representacao.Person.Resultado parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.representacao.Person.Resultado parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.representacao.Person.Resultado parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.representacao.Person.Resultado parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.representacao.Person.Resultado parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.representacao.Person.Resultado parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.representacao.Person.Resultado parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.representacao.Person.Resultado parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.representacao.Person.Resultado parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.representacao.Person.Resultado parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.representacao.Person.Resultado prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.representacao.Person.ResultadoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.representacao.Person.internal_static_representacao_Resultado_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.representacao.Person.internal_static_representacao_Resultado_fieldAccessorTable;
      }
      
      // Construct using com.representacao.Person.Resultado.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        resultado_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.representacao.Person.Resultado.getDescriptor();
      }
      
      public com.representacao.Person.Resultado getDefaultInstanceForType() {
        return com.representacao.Person.Resultado.getDefaultInstance();
      }
      
      public com.representacao.Person.Resultado build() {
        com.representacao.Person.Resultado result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.representacao.Person.Resultado buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.representacao.Person.Resultado result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.representacao.Person.Resultado buildPartial() {
        com.representacao.Person.Resultado result = new com.representacao.Person.Resultado(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultado_ = resultado_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.representacao.Person.Resultado) {
          return mergeFrom((com.representacao.Person.Resultado)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.representacao.Person.Resultado other) {
        if (other == com.representacao.Person.Resultado.getDefaultInstance()) return this;
        if (other.hasResultado()) {
          setResultado(other.getResultado());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasResultado()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              resultado_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string resultado = 1;
      private java.lang.Object resultado_ = "";
      public boolean hasResultado() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getResultado() {
        java.lang.Object ref = resultado_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          resultado_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setResultado(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resultado_ = value;
        onChanged();
        return this;
      }
      public Builder clearResultado() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultado_ = getDefaultInstance().getResultado();
        onChanged();
        return this;
      }
      void setResultado(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        resultado_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:representacao.Resultado)
    }
    
    static {
      defaultInstance = new Resultado(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:representacao.Resultado)
  }
  
  public interface ModeloOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 messageType = 1;
    boolean hasMessageType();
    int getMessageType();
    
    // required int32 requestId = 2;
    boolean hasRequestId();
    int getRequestId();
    
    // required string objectReference = 3;
    boolean hasObjectReference();
    String getObjectReference();
    
    // required string methodId = 4;
    boolean hasMethodId();
    String getMethodId();
    
    // required bytes arguments = 5;
    boolean hasArguments();
    com.google.protobuf.ByteString getArguments();
  }
  public static final class Modelo extends
      com.google.protobuf.GeneratedMessage
      implements ModeloOrBuilder {
    // Use Modelo.newBuilder() to construct.
    private Modelo(Builder builder) {
      super(builder);
    }
    private Modelo(boolean noInit) {}
    
    private static final Modelo defaultInstance;
    public static Modelo getDefaultInstance() {
      return defaultInstance;
    }
    
    public Modelo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.representacao.Person.internal_static_representacao_Modelo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.representacao.Person.internal_static_representacao_Modelo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 messageType = 1;
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private int messageType_;
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMessageType() {
      return messageType_;
    }
    
    // required int32 requestId = 2;
    public static final int REQUESTID_FIELD_NUMBER = 2;
    private int requestId_;
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getRequestId() {
      return requestId_;
    }
    
    // required string objectReference = 3;
    public static final int OBJECTREFERENCE_FIELD_NUMBER = 3;
    private java.lang.Object objectReference_;
    public boolean hasObjectReference() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getObjectReference() {
      java.lang.Object ref = objectReference_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          objectReference_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getObjectReferenceBytes() {
      java.lang.Object ref = objectReference_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        objectReference_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string methodId = 4;
    public static final int METHODID_FIELD_NUMBER = 4;
    private java.lang.Object methodId_;
    public boolean hasMethodId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getMethodId() {
      java.lang.Object ref = methodId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          methodId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMethodIdBytes() {
      java.lang.Object ref = methodId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        methodId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required bytes arguments = 5;
    public static final int ARGUMENTS_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString arguments_;
    public boolean hasArguments() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.google.protobuf.ByteString getArguments() {
      return arguments_;
    }
    
    private void initFields() {
      messageType_ = 0;
      requestId_ = 0;
      objectReference_ = "";
      methodId_ = "";
      arguments_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasObjectReference()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethodId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasArguments()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, messageType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, requestId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getObjectReferenceBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getMethodIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, arguments_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, messageType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, requestId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getObjectReferenceBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMethodIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, arguments_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.representacao.Person.Modelo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.representacao.Person.Modelo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.representacao.Person.Modelo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.representacao.Person.Modelo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.representacao.Person.Modelo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.representacao.Person.Modelo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.representacao.Person.Modelo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.representacao.Person.Modelo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.representacao.Person.Modelo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.representacao.Person.Modelo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.representacao.Person.Modelo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.representacao.Person.ModeloOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.representacao.Person.internal_static_representacao_Modelo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.representacao.Person.internal_static_representacao_Modelo_fieldAccessorTable;
      }
      
      // Construct using com.representacao.Person.Modelo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        messageType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        requestId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        objectReference_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        methodId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        arguments_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.representacao.Person.Modelo.getDescriptor();
      }
      
      public com.representacao.Person.Modelo getDefaultInstanceForType() {
        return com.representacao.Person.Modelo.getDefaultInstance();
      }
      
      public com.representacao.Person.Modelo build() {
        com.representacao.Person.Modelo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.representacao.Person.Modelo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.representacao.Person.Modelo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.representacao.Person.Modelo buildPartial() {
        com.representacao.Person.Modelo result = new com.representacao.Person.Modelo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.objectReference_ = objectReference_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.methodId_ = methodId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.arguments_ = arguments_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.representacao.Person.Modelo) {
          return mergeFrom((com.representacao.Person.Modelo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.representacao.Person.Modelo other) {
        if (other == com.representacao.Person.Modelo.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasObjectReference()) {
          setObjectReference(other.getObjectReference());
        }
        if (other.hasMethodId()) {
          setMethodId(other.getMethodId());
        }
        if (other.hasArguments()) {
          setArguments(other.getArguments());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMessageType()) {
          
          return false;
        }
        if (!hasRequestId()) {
          
          return false;
        }
        if (!hasObjectReference()) {
          
          return false;
        }
        if (!hasMethodId()) {
          
          return false;
        }
        if (!hasArguments()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              messageType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              requestId_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              objectReference_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              methodId_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              arguments_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 messageType = 1;
      private int messageType_ ;
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMessageType() {
        return messageType_;
      }
      public Builder setMessageType(int value) {
        bitField0_ |= 0x00000001;
        messageType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 requestId = 2;
      private int requestId_ ;
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getRequestId() {
        return requestId_;
      }
      public Builder setRequestId(int value) {
        bitField0_ |= 0x00000002;
        requestId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        requestId_ = 0;
        onChanged();
        return this;
      }
      
      // required string objectReference = 3;
      private java.lang.Object objectReference_ = "";
      public boolean hasObjectReference() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getObjectReference() {
        java.lang.Object ref = objectReference_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          objectReference_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setObjectReference(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        objectReference_ = value;
        onChanged();
        return this;
      }
      public Builder clearObjectReference() {
        bitField0_ = (bitField0_ & ~0x00000004);
        objectReference_ = getDefaultInstance().getObjectReference();
        onChanged();
        return this;
      }
      void setObjectReference(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        objectReference_ = value;
        onChanged();
      }
      
      // required string methodId = 4;
      private java.lang.Object methodId_ = "";
      public boolean hasMethodId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getMethodId() {
        java.lang.Object ref = methodId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          methodId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMethodId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        methodId_ = value;
        onChanged();
        return this;
      }
      public Builder clearMethodId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        methodId_ = getDefaultInstance().getMethodId();
        onChanged();
        return this;
      }
      void setMethodId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        methodId_ = value;
        onChanged();
      }
      
      // required bytes arguments = 5;
      private com.google.protobuf.ByteString arguments_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasArguments() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.google.protobuf.ByteString getArguments() {
        return arguments_;
      }
      public Builder setArguments(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        arguments_ = value;
        onChanged();
        return this;
      }
      public Builder clearArguments() {
        bitField0_ = (bitField0_ & ~0x00000010);
        arguments_ = getDefaultInstance().getArguments();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:representacao.Modelo)
    }
    
    static {
      defaultInstance = new Modelo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:representacao.Modelo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_representacao_Pessoa_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_representacao_Pessoa_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_representacao_Resultado_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_representacao_Resultado_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_representacao_Modelo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_representacao_Modelo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Agenda.proto\022\rrepresentacao\"B\n\006Pessoa\022" +
      "\014\n\004nome\030\001 \002(\t\022\020\n\010endereco\030\002 \002(\t\022\030\n\020numer" +
      "oDeTelefone\030\003 \002(\t\"\036\n\tResultado\022\021\n\tresult" +
      "ado\030\001 \002(\t\"n\n\006Modelo\022\023\n\013messageType\030\001 \002(\005" +
      "\022\021\n\trequestId\030\002 \002(\005\022\027\n\017objectReference\030\003" +
      " \002(\t\022\020\n\010methodId\030\004 \002(\t\022\021\n\targuments\030\005 \002(" +
      "\014B\033\n\021com.representacaoB\006Person"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_representacao_Pessoa_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_representacao_Pessoa_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_representacao_Pessoa_descriptor,
              new java.lang.String[] { "Nome", "Endereco", "NumeroDeTelefone", },
              com.representacao.Person.Pessoa.class,
              com.representacao.Person.Pessoa.Builder.class);
          internal_static_representacao_Resultado_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_representacao_Resultado_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_representacao_Resultado_descriptor,
              new java.lang.String[] { "Resultado", },
              com.representacao.Person.Resultado.class,
              com.representacao.Person.Resultado.Builder.class);
          internal_static_representacao_Modelo_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_representacao_Modelo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_representacao_Modelo_descriptor,
              new java.lang.String[] { "MessageType", "RequestId", "ObjectReference", "MethodId", "Arguments", },
              com.representacao.Person.Modelo.class,
              com.representacao.Person.Modelo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
